### ISSUE TITLE
where is fries file allocated?

### ISSUE THREAD

**Issue by arsnyder16** [misko/bigmaac#5]
I am simply reviewing your code and I can't seem to see where the fries file is allocated?
`FRIES are sent to a preallocated 512GB (env variable SIZE_FRIES) virtual address space, the total of which is backed by its own single file on the swap partition.`

I see the virtual address space being allocated
`base_fries = mmap(NULL, size_total, PROT_READ | PROT_WRITE, MAP_ANONYMOUS | MAP_PRIVATE, -1, 0);`

The only file backed memory is coming from `mmap_tmpfile`
which only is called for allocation of the big maac? 
```
 if (head==_head_bigmaacs) {
        mmap_tmpfile(heap_chunk->ptr,size);
    }
```

**Comment by misko** [comment]
Hey, you are totally right! I don't think the fries are on disk 🤦‍♂️ , working on this today!

**Comment by misko** [comment]
This should be fixed now! still testing a bit

**Comment by misko** [comment]
Fries file allocated and tested :tada: thank you for filing the issue!
