### ISSUE TITLE
Support for ENOMEM

### ISSUE THREAD

**Issue by arsnyder16** [misko/bigmaac#6]
There are various places where BigMaac could report ENOMEM and return NULL.

Some applications are coded to gracefully error when there is not enough memory to perform calculations so BigMaac could set `errno = ENOMEM;` and return NULL.

This would be useful in situations where the following env variables are set `SIZE_BIGMAAC` `SIZE_FRIES`, this would allow users to somewhat mimic k8s resource limits for pods  

Notable locations within the current codebase that could report ENOMEM:
`fprintf(stderr,"BigMaac : Failed to find available space\n");`

` fprintf(stderr,"There is no free memory!\n");`

**Comment by misko** [comment]
This makes total sense. I wasn't sure the best way to handle the errors and pass them back up. ENOMEM / NULL is a great way. I will add that today :)

**Comment by misko** [comment]
Added base support for ENOMEM , need to work on better error handling and passing up back to system
